/**
 * Proactive Prompt interface
 * Represents a prompt generated by the prompting service to remind users about tasks
 */
export interface ProactivePrompt {
  /** Unique ID for this prompt instance */
  promptId: string;
  /** ID of the task being prompted */
  taskId: string;
  /** Text of the task being prompted */
  taskText: string;
  /** ISO 8601 timestamp when the prompt was generated */
  promptedAt: string;
  /** True if this is the user's first prompt (for showing education overlay) */
  isFirstPrompt?: boolean;
  /** Optional follow-up message to display (e.g., encouragement after first prompt) */
  followUpMessage?: string;
}

/**
 * Prompt response types
 * Represents how a user responded to a prompt
 */
export type PromptResponse = 'complete' | 'dismiss' | 'snooze' | 'timeout';

/**
 * Prompt Event interface
 * Represents a logged prompt event for analytics tracking
 */
export interface PromptEvent {
  /** Unique ID for this prompt event */
  promptId: string;
  /** ID of the task that was prompted */
  taskId: string;
  /** ISO 8601 timestamp when the prompt was generated */
  promptedAt: string;
  /** User's response to the prompt */
  response: PromptResponse;
  /** ISO 8601 timestamp when user responded, null if timeout */
  respondedAt: string | null;
}

/**
 * Prompt Analytics interface
 * Represents aggregated analytics data about prompt responses
 */
export interface PromptAnalytics {
  /** Prompt response rate as a percentage (0-100) */
  promptResponseRate: number;
  /** Breakdown of responses by type */
  responseBreakdown: Record<PromptResponse, number>;
  /** Average response time in milliseconds */
  averageResponseTime: number;
}

/**
 * Snooze Prompt DTO
 * Request payload for snoozing a prompt
 */
export interface SnoozePromptDto {
  /** ID of the task to snooze */
  taskId: string;
}
