/**
 * Proactive Prompt interface
 * Represents a prompt generated by the prompting service to remind users about tasks
 */
export interface ProactivePrompt {
  /** ID of the task being prompted */
  taskId: string;
  /** Text of the task being prompted */
  taskText: string;
  /** ISO 8601 timestamp when the prompt was generated */
  promptedAt: string;
}
